config/routes.rb
Rails.application.routes.draw do
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :author, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
    @comment = Comment.new
  end

  def create
    @comments = Comment.all
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comments_path }
        format.js
      else
        format.html { render :index }
        format.js
      end
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.author %>:</strong> <%= comment.body %>
</p>

app/views/comments/_comment_form.html.erb
<%= form_for comment, remote: true do |f| %>
    <div><%= f.label :author %>
      <br/><%= f.text_field :author %></div>
    <div><%= f.label :body %>
      <br/><%= f.text_area :body %></div>
    <%= f.submit %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
// j = escape_javascript
<% if @comment.valid? %>
    $('#comments').append('<%=j render partial: 'comment', object: @comment %>');
    $('#new_comment textarea').val('').focus();
<% else %>
    $('#new_comment').replaceWith('<%=j render partial: 'comment_form', object: @comment, as: :comment %>')
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<div id="comments">
  <%= render partial: 'comment', collection: @comments %>
</div>

<%= render partial: 'comment_form', object: @comment, as: :comment %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comments</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>